//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public int PDF_ID { get; set; }
        public int ARTICLE_ID { get; set; }
        public int FILE_TYPE_ID { get; set; }
        public string PDF_NAME { get; set; }
        public string PDF_URL { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual FILE_TYPE FILE_TYPE { get; set; }
    }
}
