//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIC
    {
        public int PERSON_ID { get; set; }
        public int ARTICLE_ID { get; set; }
        public int STATUS_ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
