//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG
    {
        public IMG()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
        }
    
        public int IMG_ID { get; set; }
        public string IMG_ALT { get; set; }
        public string IMG_NAME { get; set; }
        public string IMG_CREDITS { get; set; }
        public string IMG_LEGEND { get; set; }
        public string IMG_SRC { get; set; }
        public string IMG_URL { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
    }
}
