//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.HISTORIC = new HashSet<HISTORIC>();
        }
    
        public int STATUS_ID { get; set; }
        public string STATUS_LABEL { get; set; }
    
        public virtual ICollection<HISTORIC> HISTORIC { get; set; }
    }
}
