//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEME
    {
        public THEME()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
        }
    
        public int THEME_ID { get; set; }
        public string THEME_LABEL { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
    }
}
