//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public VIDEO()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
        }
    
        public int IMG_ID2 { get; set; }
        public string VIDEO_ALT { get; set; }
        public string VIDEO_NAME { get; set; }
        public string VIDEO_CREDITS { get; set; }
        public string VIDEO_LEGEND { get; set; }
        public string VIDEO_MARKUP { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
    }
}
