//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class FILE
    {
        [Key]
        public int FILE_ID { get; set; }
        public int ARTICLE_ID { get; set; }
        public int FILE_TYPE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_URL { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual FILE_TYPE FILE_TYPE { get; set; }
    }
}
