//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FILE_TYPE
    {
        public FILE_TYPE()
        {
            this.FILE = new HashSet<FILE>();
        }
    
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FILE_TYPE_ID { get; set; }
        public string FILE_TYPE_LABEL { get; set; }
    
        public virtual ICollection<FILE> FILE { get; set; }
    }
}
