//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ADT.Workflow.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class HISTORIC
    {
        [Key][Column(Order = 0)]
        public int PERSON_ID { get; set; }
        [Key][Column(Order = 1)]
        public int ARTICLE_ID { get; set; }
        [Key][Column(Order = 2)]
        public int STATUS_ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
