//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADT.Workflow.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VIDEO
    {
        public VIDEO()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
        }
    
        [Key]
        public int VIDEO_ID { get; set; }
        public string VIDEO_ALT { get; set; }
        public string VIDEO_NAME { get; set; }
        public string VIDEO_CREDITS { get; set; }
        public string VIDEO_LEGEND { get; set; }
        public string VIDEO_MARKUP { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
    }
}
